### ISSUE TITLE
classserver.pxd file not found

### ISSUE THREAD

**Issue by arvinpan** [chenesan/opencog-to-minecraft#1]
README says:
1.put the classserver.pxd in atomspace/opencog/cython/opencog. It's for updating the atom types after adding spacetime module.

But I cannot find classserver.pxd file, there's only classserver.pyx under src/opencog/ directory.

Please tell me if I misunderstood something, many thanks!

**Comment by chenesan** [comment]
Hi,
The development of opencog-to-minecraft has been moved to 
https://github.com/OC2MC/opencog-to-minecraft
I think the README should work in opencog side for now. If you meet problems just ask me; We haven't had a stable working flow to start the pipeline from Minecraft to Opencog so you may have to read the code to know how that works. And I don't exactly know the situation of mapNode(a ROS node bridges the Minecraft and Opencog). About that you should ask Brad (https://github.com/LucidBlue). He's working on that..

**Comment by arvinpan** [comment]
I see. I will follow the new branch. 
Thank you so much for your kind introduction. Issue closed :)
